version: "3"
services:
  python:
    build: .
    ports: ['5000:5000']
    volumes:
      - "./packages/python/src:/app"
      - "./shared/images:/app/shared/images"
      - "./shared/audios:/app/shared/audios"